# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
#  vmImage: 'ubuntu-latest'
  vmImage: 'DESKTOP-MLO3EF6'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g imp-central-impt
    npm install -g Builder
  displayName: 'npm install and build'

- script: |
    ls
    impt test run
  displayName: 'tests'